// generated by stringer -type=MessageType; DO NOT EDIT

package dhcp4

import "fmt"

const _MessageType_name = "DiscoverOfferRequestDeclineACKNAKReleaseInform"

var _MessageType_index = [...]uint8{8, 13, 20, 27, 30, 33, 40, 46}

func (i MessageType) String() string {
	i -= 1
	if i >= MessageType(len(_MessageType_index)) {
		return fmt.Sprintf("MessageType(%d)", i+1)
	}
	hi := _MessageType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _MessageType_index[i-1]
	}
	return _MessageType_name[lo:hi]
}
